
name: Terraform Destroy

on:
  push:
  workflow_dispatch:  # manual trigger execution

# set bash as default runner 
defaults:
  run:
    shell: bash

jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
  
    steps: 
    - name: Checkout
      uses: actions/checkout@master

    - name: GCP Service Account auth
      id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Terraform destoy
      id: tf_destoy
      run: |
        terraform init
        terraform destroy --auto-approve